import React from 'react'
import * as S from './styles'

export default function Cards() {
	// const cards = []

	return (
		<S.CotainerCards>
			<S.Cards>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
				<S.Card>
					<S.ImageContainer>
						<S.ImagePoke
							src="https://i.pinimg.com/originals/45/cc/a6/45cca677424b9c0e3c75d94722813d9a.png"
							alt="pokemon"
						/>
					</S.ImageContainer>
					<S.BodyCard>
						<S.LabelNumber>Nª 001</S.LabelNumber>
						<S.LabelName>Charizard</S.LabelName>
						<S.Types>
							<S.Type>Fire</S.Type>
						</S.Types>
					</S.BodyCard>
				</S.Card>
			</S.Cards>
		</S.CotainerCards>
	)
}
